version: '3'

services:
  dashboard-api:
    container_name: dashboard-api
    image: dashboard-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - /storage:/storage:rw
      - /keys.json:/keys.json:ro
      - /keys:/keys:ro
      - /logs:/logs:rw